version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
      
  restaurant-system:
    image: ${DOCKER_REGISTRY-}restaurantsystem
    build:
      context: .
      dockerfile: restaurant-system/Dockerfile
    depends_on:
      - db